#!/usr/bin/env node

var cli = require('commander'),
    package = require('./package.json');

cli._name = 'adafruit-io';

cli
  .version(package.version)
  .command('server [cmd]', 'Local Adafruit IO server')
  .command('tunnel [cmd]', 'io.adafruit.com TLS tunnel')
  .parse(process.argv);

if (!process.argv.slice(2).length)
  cli.outputHelp();
