'use strict';

// generated by: https://github.com/adafruit/io-swagger-templates
// using the Adafruit IO Swagger docs: https://io.adafruit.com/api/docs/api.json
const util = require('util'),
      Model = require('./Base');

class Error extends Model {

  constructor(properties) {
    super(properties);
  }

  static type() {
    return 'Error';
  }

  static fields() {
    return [
      'error'
    ];
  }

}

exports = module.exports = Error;

