'use strict';

// generated by: https://github.com/adafruit/io-swagger-templates
// using the Adafruit IO Swagger docs: https://io.adafruit.com/api/docs/api.json
const xml = require('xml'),
      Data = require('../models/Data');

module.exports.feedsFeedIdDataGet = function feedsFeedIdDataGet(req, res, next) {

  const feedId = req.swagger.params['feed_id'].value;

  Data.feedsFeedIdDataGet(feedId)
    .then(handle_response.bind(this, res))
    .catch(handle_error.bind(this, res));

};


module.exports.getDataById = function getDataById(req, res, next) {

  const feedId = req.swagger.params['feed_id'].value,
      dataId = req.swagger.params['data_id'].value;

  Data.getDataById(feedId, dataId)
    .then(handle_response.bind(this, res))
    .catch(handle_error.bind(this, res));

};


const handle_response = function(res, data) {
  res.format({
    'application/json': function() {
      res.json(data);
    },
    'text/csv': function() {
      res.csv(data);
    },
    'application/xml': function() {
      res.set('Content-Type', 'text/xml');
      res.send(xml(data));
    },
    'text/html': function() {
      res.set('Content-Type', 'application/json');
      res.json(data);
    },
    'default': function() {
      res.set('Content-Type', 'application/json');
      res.json(data);
    }
  });
};

const handle_error = function(res, err) {
  res.format({
    'application/json': function() {
      res.status(500).json({ error: err });
    },
    'text/csv': function() {
      res.status(500).csv(err);
    },
    'application/xml': function() {
      res.set('Content-Type', 'text/xml');
      res.status(500).send(xml({ error: err }));
    },
    'text/html': function() {
      res.set('Content-Type', 'application/json');
      res.status(500).json({ error: err });
    },
    'default': function() {
      res.set('Content-Type', 'application/json');
      res.status(500).json({ error: err });
    }
  });
};
