'use strict';

// generated by: https://github.com/adafruit/io-swagger-templates
// using the Adafruit IO Swagger docs: https://io.adafruit.com/api/docs/api.json
const xml = require('xml'),
      Data = require('../models/Data');

module.exports.all = function all(req, res, next) {

  const feedId = req.swagger.params['feed_id'].value;

  Data.all(feedId)
    .then(handle_response.bind(this, res))
    .catch(handle_error.bind(this, res));

};


module.exports.create = function create(req, res, next) {

  const feedId = req.swagger.params['feed_id'].value,
        group = req.swagger.params['group'].value;

  Data.create(feedId, group)
    .then(handle_response.bind(this, res))
    .catch(handle_error.bind(this, res));

};


module.exports.last = function last(req, res, next) {

  const feedId = req.swagger.params['feed_id'].value;

  Data.last(feedId)
    .then(handle_response.bind(this, res))
    .catch(handle_error.bind(this, res));

};


module.exports.next = function next(req, res, next) {

  const feedId = req.swagger.params['feed_id'].value;

  Data.next(feedId)
    .then(handle_response.bind(this, res))
    .catch(handle_error.bind(this, res));

};


module.exports.previous = function previous(req, res, next) {

  const feedId = req.swagger.params['feed_id'].value;

  Data.previous(feedId)
    .then(handle_response.bind(this, res))
    .catch(handle_error.bind(this, res));

};


module.exports.receive = function receive(req, res, next) {

  const feedId = req.swagger.params['feed_id'].value;

  Data.receive(feedId)
    .then(handle_response.bind(this, res))
    .catch(handle_error.bind(this, res));

};


module.exports.send = function send(req, res, next) {

  const feedId = req.swagger.params['feed_id'].value,
        group = req.swagger.params['group'].value;

  Data.send(feedId, group)
    .then(handle_response.bind(this, res))
    .catch(handle_error.bind(this, res));

};


module.exports.get = function get(req, res, next) {

  const feedId = req.swagger.params['feed_id'].value,
        id = req.swagger.params['id'].value;

  Data.get(feedId, id)
    .then(handle_response.bind(this, res))
    .catch(handle_error.bind(this, res));

};


module.exports.replace = function replace(req, res, next) {

  const feedId = req.swagger.params['feed_id'].value,
        id = req.swagger.params['id'].value,
        group = req.swagger.params['group'].value;

  Data.replace(feedId, id, group)
    .then(handle_response.bind(this, res))
    .catch(handle_error.bind(this, res));

};


module.exports.destroy = function destroy(req, res, next) {

  const feedId = req.swagger.params['feed_id'].value,
        id = req.swagger.params['id'].value;

  Data.destroy(feedId, id)
    .then(handle_response.bind(this, res))
    .catch(handle_error.bind(this, res));

};


module.exports.update = function update(req, res, next) {

  const feedId = req.swagger.params['feed_id'].value,
        id = req.swagger.params['id'].value,
        group = req.swagger.params['group'].value;

  Data.update(feedId, id, group)
    .then(handle_response.bind(this, res))
    .catch(handle_error.bind(this, res));

};


const handle_response = function(res, data) {
  res.format({
    'application/json': function() {
      res.json(data);
    },
    'text/csv': function() {
      res.csv(data);
    },
    'application/xml': function() {
      res.set('Content-Type', 'text/xml');
      res.send(xml(data));
    },
    'text/html': function() {
      res.set('Content-Type', 'application/json');
      res.json(data);
    },
    'default': function() {
      res.set('Content-Type', 'application/json');
      res.json(data);
    }
  });
};

const handle_error = function(res, err) {
  res.format({
    'application/json': function() {
      res.status(500).json({ error: err });
    },
    'text/csv': function() {
      res.status(500).csv(err);
    },
    'application/xml': function() {
      res.set('Content-Type', 'text/xml');
      res.status(500).send(xml({ error: err }));
    },
    'text/html': function() {
      res.set('Content-Type', 'application/json');
      res.status(500).json({ error: err });
    },
    'default': function() {
      res.set('Content-Type', 'application/json');
      res.status(500).json({ error: err });
    }
  });
};
